### ISSUE TITLE
Issue In ContolFx dependency

### ISSUE THREAD

**Issue by kavya25** [MartinanderssonDotcom/secure-login-file-transfer#1]
![capture](https://cloud.githubusercontent.com/assets/18423127/23101438/672eea6e-f6b9-11e6-9076-8c7f6f4affd5.PNG)

When i try to connect to the server i am getting the above error,can somebody help me in fixing the error
Thanks in Advance

**Comment by martinandersson** [comment]
See if my latest commit helps.

Bottom line is that ControlsFX fuct up a long time ago building into their code base dependencies on [non-public API:s](http://fxexperience.com/2015/08/controlsfx-and-javafx-8u60/).

Also, ControlsFX scrapped their Dialog API since it was included in JavaFX 8u40, albeit totally refactored.

What I committed:

1. Changed our code to use the official JavaFX API for dialogs.
2. Updated the dependency to the latest and greatest ControlsFX (still using their `ProgressDialog`)
3. Made Maven copy the dependencies for the client app to a "lib" dir and reference those in the MANIFEST.mf file
4. Updated suggested connect URLs in the client app.

This will probably work for you in your environment, I hope, but will on the other hand brake old environments running old JRE:s lol. But I don't really care too much since I specified in this project's README.md file that one should always use "the latest JDK".

An README.md file not specifying which runtime is a minimum requirement is, of course, a problem. The screen shots are also out-of-date since the visuals have changed somewhat. Please feel free to address these issues. Otherwise, I will probably do something about it in my next life.

Thank you for submitting the issue. Let me know if this solved your problems. If I don't hear from you in a few days I will consider the issue resolved.
